spring.application.name=LJ-PLANT-HIRE-BACKEND

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/lj_plant_hire?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=Tshepo
spring.datasource.password=Se#493456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true